version: '3.7'

services:
    db:
        restart: always
        image: mysql:8.0.22
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - mysql_data:/var/lib/mysql/
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=espotest
            - MYSQL_USER=root
            - MYSQL_PASSWORD=espotestpassword
            - MYSQL_ROOT_PASSWORD=espotestpassword

    web:
        restart: always
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./ESPOTest/:/ESPOTest/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on: 
            - "db"

volumes:
    mysql_data:

